=== markuus83/Repositorios/DTD & XSD/DTD/Exercise 3/message.dtd
<!ELEMENT message (from,to+,subjec,attachment+)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT subjec (#PCDATA)>
<!ELEMENT attachment (#PCDATA)>

=== markuus83/Repositorios/DTD & XSD/DTD/Exercise 3/message.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE message SYSTEM "message.dtd">

<message>
    <from>maria@gmail.com</from>
    <to>ignacio@gmail.com</to>
    <to>cristina@edu.xunta.gal</to>
    <subjec>Sending files</subjec>
    <attachment>D:\photos\phishing.jpg</attachment>
    <attachment>D:\docs\letter.odt</attachment>
    <attachment>D:\fotos\dinner.jpg</attachment>
</message>
