<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE stock [
    <!ELEMENT stock (new-car|used-car)*>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>

<stock>
    <new-car>
        <model>Ford Mustang Shelby</model>
        <price>50.000€</price>
    </new-car>

    <new-car>
        <model>Ford Mustang Gt550</model>
        <price>40.000€</price>
    </new-car>

    <used-car>
        <model>BMW M4</model>
        <price>30.000€</price>
        <mileage>100.000</mileage>
        <condition>Good</condition>
    </used-car>
</stock>