=== markuus83/Repositorios/DTD & XSD/XSD/Exercise 27/youtube.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="youtube">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="videos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="video">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="url" type="xs:string" />
                                        <xs:element name="views" type="xs:string" />
                                        <xs:element name="comments">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="good" type="xs:string" />
                                                    <xs:element name="bad" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="subscribers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="subscriber">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="subscriptionDate">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="day" type="xs:integer" use="required" />
                                                                        <xs:attribute name="month" use="required" />
                                                                        <xs:attribute name="year" type="xs:integer" use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="comments">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="quantity" type="xs:integer" use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="email">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="user" type="xs:string" />
                                                                            <xs:element name="server">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="gmail" />
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="completo" use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="language" type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="code" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="advertisement">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="company" type="xs:string" />
                                        <xs:element name="bannersPerMinute" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sponsoredAd">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="company" type="xs:string" />
                                        <xs:element name="bannersPerMinute" type="xs:string" />
                                        <xs:element name="youTubeDiscount" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="sponsor" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="availableLanguages" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== markuus83/Repositorios/DTD & XSD/XSD/Exercise 27/youtube.xml
<?xml version="1.0" encoding="UTF-8"?>
<youtube xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="youtube.xsd">
    <videos>
        <video>XSD Overview <url>https://www.youtube.com/watch?v=PpvX3izvRWU</url>
			<views>112000</views>

			<comments>
                <good>1200</good>
                <bad>700</bad>
            </comments>

			<subscribers>
                <subscriber code="15-[AR]-56">
                    <subscriptionDate day="12" month="february" year="2023" />
                    <comments quantity="12" />
                    <email completo="rafa@gmail.com">
                        <user>rafa</user>
                        <server>
                            <gmail />
                        </server>
                    </email>
                    <language>Korean</language>
                </subscriber>
            </subscribers>
        </video>
    </videos>

    <advertisement>
        <ad>
            <company>Seresco</company>
            <bannersPerMinute>40000</bannersPerMinute>
        </ad>

        <sponsoredAd sponsor="Google">
            <company>Gadis</company>
            <bannersPerMinute>15000</bannersPerMinute>
            <youTubeDiscount>23%</youTubeDiscount>
        </sponsoredAd>

    </advertisement>
    <availableLanguages>French Italian German English Chinese Korean Japanese</availableLanguages>
</youtube>

<!-- 

1. The subscriptionDate and comments elements must be empty elements.

2. The video elements must be of mixed content.

3. The subscriber code attribute must comply with the following rules: two numbers, one - character
and one [, two capital letters, one ] character, one - character and two numbers.

4. The server elements must have only one of the following children: gmail, hotmail or
iessanclemente.net.

5. The year attribute must have a number between 2020 and 2023.

6. The value of the availableLanguages element must take its value from the following list of
values:
French, Italian, German, English, Chinese, Korean and Japanese. Use a list.

7. The content of the views elements must have a minimum value of 0 and a maximum value of
100000000.
The content of good elements must be of a type that extends the type of the views element but must
fall between 0 and 200000.

-->
