=== markuus83/Repositorios/DTD & XSD/XSD/Exercise 23/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"/>
            <xs:enumeration value="Small"/>
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="photo" type="xs:string" />
                            <xs:element name="tags" type="xs:string" />
                            <xs:element name="diameter" type="xs:integer" minOccurs="0" />
                            <xs:element name="weight" type="xs:integer" minOccurs="0" />
                            <xs:element name="price" type="xs:decimal" />
                            <xs:element name="sizeField" type="sizeType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- 

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"/>
            <xs:enumeration value="Small"/>
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="photo" type="xs:string"/>
                            <xs:element name="tags" type="xs:string"/>
                            <xs:element name="diameter" type="xs:positiveInteger"/>
                            <xs:element name="weight" type="xs:positiveInteger"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="sizeField" type="sizeType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

-->

=== markuus83/Repositorios/DTD & XSD/XSD/Exercise 23/items.xml
<?xml version="1.0" encoding="UTF-8"?>

<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="items.xsd">
    <item>
        <name>Maricon</name>
        <photo>Maricon</photo>
        <tags>Maricon</tags>
        <diameter>2</diameter>
        <weight>3</weight>
        <price>4.02</price>
        <sizeField>Big</sizeField>
    </item>

    <item>
        <name>Maricon</name>
        <photo>Maricon</photo>
        <tags>Maricon</tags>
        <diameter>2</diameter>
        <weight>3</weight>
        <price>4.01</price>
        <sizeField>Small</sizeField>
    </item>

    <item>
        <name>Maricon</name>
        <photo>Maricon</photo>
        <tags>Maricon</tags>
        <diameter>2</diameter>
        <weight>3</weight>
        <price>4.07</price>
        <sizeField></sizeField>
    </item>
</items>
