<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE message [
    <!ELEMENT message (from, to+, subjec, attachment+)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT subjec (#PCDATA)>
    <!ELEMENT attachment (#PCDATA)>
]>

<message>
    <from>maria@gmail.com</from>
    <to>ignacio@gmail.com</to>
    <to>cristina@edu.xunta.gal</to>
    <subjec>Sending files</subjec>
    <attachment>D:\photos\phishing.jpg</attachment>
    <attachment>D:\docs\letter.odt</attachment>
    <attachment>D:\fotos\dinner.jpg</attachment>
</message>