=== markuus83/Repositorios/DTD & XSD/DTD/Exercise 6/booklist.dtd
<!ELEMENT booklist (book+)>
<!ELEMENT book (bookname*,author+,price?,homepage)>
<!ELEMENT bookname (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>

=== markuus83/Repositorios/DTD & XSD/DTD/Exercise 6/booklist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">

<booklist>
    <book>
        <bookname>Ola</bookname>
        <author>Ola</author>
        <price>Ola</price>
        <homepage>Ola</homepage>
    </book>

    <book>
        <author>Ola</author>
        <author>Ola</author>
        <price>Ola</price>
        <homepage>Ola</homepage>
    </book>

    <book>
        <bookname>Ola</bookname>
        <author>Ola</author>
        <homepage>Ola</homepage>
    </book>

    <book>
        <bookname>Ola</bookname>
        <bookname>Ola</bookname>
        <author>Ola</author>
        <price>Ola</price>
        <homepage>Ola</homepage>
    </book>
</booklist>
